# Generated by Django 5.0.6 on 2024-07-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='sales_department',
            field=models.ManyToManyField(blank=True, related_name='managers', to='users.salesdepartment'),
        ),
    ]
