# Generated by Django 5.0.6 on 2024-07-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_client_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, unique=True),
        ),
    ]
