# Generated by Django 5.0.6 on 2024-07-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_manager_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
