# Generated by Django 5.0.6 on 2024-07-03 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_car_client_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='users.car'),
        ),
    ]
