# Generated by Django 5.0.6 on 2024-07-03 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_client_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='car',
        ),
        migrations.AddField(
            model_name='car',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='users.client'),
        ),
    ]
