# Generated by Django 5.0.6 on 2024-07-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_client_car_car_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='client',
            new_name='owner',
        ),
    ]
