# Generated by Django 5.0.6 on 2024-07-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='manager_commentary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
