# Generated by Django 5.0.6 on 2024-07-03 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_manager_commentary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='vin_code',
        ),
    ]
