# Generated by Django 5.0.6 on 2024-07-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
    ]
